export const colors = {
    RED: '#e57373',
    PINK: '#f06292',
    PURPLE: '#ba68c8',
    DEEP_PURPLE: '#9575cd',
    INDIGO: '#7986cb',
    BLUE: '#64b5f6',
    CYAN: '#4dd0e1',
    TEAL: '#4db6ac',
    GREEN: '#81c784',
    LIME: '#dce775',
    YELLOW: '#fff176',
    ORANGE: '#ffb74d',
    GREY: '#e0e0e0',
    WHITE: '#f5f5f5',
};

export const colorNames = {
    RED: 'RED',
    PINK: 'PINK',
    PURPLE: 'PURPLE',
    DEEP_PURPLE: 'DEEP_PURPLE',
    INDIGO: 'INDIGO',
    BLUE: 'BLUE',
    CYAN: 'CYAN',
    TEAL: 'TEAL',
    GREEN: 'GREEN',
    LIME: 'LIME',
    YELLOW: 'YELLOW',
    ORANGE: 'ORANGE',
    GREY: 'GREY',
    WHITE: 'WHITE',
};
